# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "awSWtSk+VmtOn2OXIGyDr7msnq97rQnzRhklPCPwCQZBBunNYGPVo2YanVKtHqcy6PeC9OZd6ZQu4fuuk3rDAGlAruwUY+YH6bODxa7j80zuq4Qgywq47/xPRWps3L3Qd73mj77qnh78dlZ6/d+xTbv5z/h02CyevMOuEw1Jz15onIDHUHFdAV2myUg5CNXxVCUqAwiHjaXuQ8YTSgtnRNaOcFeRrni7XtNPCSrQQeB9pBVuMUpSVU3eLPMbqIRH/Rl+227bKv3KzQeDWM9ukhLqhhE2L3KcwIXYK3106NgHaPqj2gc8svu1LEmxAYh/3VEcmdNUPuCLvo4yGezgg/5TlIhQVBTWxFmCWWQey48nJz0WVSeZA1pq4jnDg6ysalROC4kSUAPW5UC//5mcfoNTVxEes2PZd/txjoD9SH8JDp6WeCkGwuPKHvhZKT5vOmGyV1k5n5k9IA/WTbB7Q74lHYmXke0mewrOsFDJht7eWHJU0jzjDLoMBt5PYs+a2Bc6/43i9s8LWNeayZfvuhLKgcHNzCDqnvZ+n2WvY5HJWOXlFeFh3l08HiuPP5dSMXbNiGXdb18GS/D3rP+XPmrWHQdTgYZ0AcKFwV0paxO133C5NLKZgqzGBjJui1JL/hY1uUTFz+hoSbQRsf0wtmV0njpG2KaWIVpakl9Y/zQ="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
